### ISSUE TITLE
Error during Make

### ISSUE THREAD

**Issue by Slept-Warrior** [magic282/One-Key-L2TP-IKEV2-Setup#1]
make[4]: **\* [kernel_netlink_ipsec.lo] 错误 1
make[4]: Leaving directory `/etc/strongswan-5.3.3/src/libhydra/plugins/kernel_netlink'
make[3]: *** [all-recursive] 错误 1
make[3]: Leaving directory`/etc/strongswan-5.3.3/src/libhydra'
make[2]: **\* [all-recursive] 错误 1
make[2]: Leaving directory `/etc/strongswan-5.3.3/src'
make[1]: *** [all-recursive] 错误 1
make[1]: Leaving directory`/etc/strongswan-5.3.3'
make: **\* [all] 错误 2

**Comment by magic282** [comment]
@Slept-Warrior 你这是哪家的vps，什么系统啊？

**Comment by Slept-Warrior** [comment]
抱歉之前没有讲清楚，刚刚午休一会儿午饭，正好上来补充一下
VPS: conoha-JP
OS: CentOS6.6(with LAMP running)

目前现象：
1)在CentOS6.6中5.3.3 make不成功(纯./configure后make也不成功)；
2)方才修改sh下载5.3.0安装成功(后续未测试)

故猜测：5.3.3与CentOS6.6不兼容(待证实)

建议：不同OS下载不同版本strongswan，推荐参考rpm源的版本，链接：http://pkgs.org/download/strongswan

**Comment by magic282** [comment]
@Slept-Warrior 这个是这样。。。这个只在Ubuntu和Debian下测试过。。。CentOS没有测试。。。而且在Debian系的发行版下用apt安装的strongswan也不能用，不知道为什么，所以才在代码里直接跳过了apt安装的部分

**Comment by Slept-Warrior** [comment]
不不不，我并没有在CentOS中装RPM包，我的意思是：
1)脚本下载的是最新release，即5.3.3;
2)这个5.3.3在我上述环境中make失败;
3)通过修改一键脚本让其下载5.3.0，安装成功;

同时，我观察到：rpm源中CentOS项的strongswan版本是5.3.2，ALT Linux Sisyphus项的该软件是5.3.3。

于是，我猜测有兼容性问题(虽说待证实的建议是流氓，但是好想爽爽的流氓一把)。

**Comment by Slept-Warrior** [comment]
刚刚吐槽有误，以为你和某个博主是同一个人....

从博客导流到这里直接奔着issue去了...没想到不是一个人 项目有修改 :P

**Comment by magic282** [comment]
@Slept-Warrior orz什么博客。。。
